### ISSUE TITLE
Dataset not found (running in a google colab sheet)

### ISSUE THREAD

**Issue by A7F** [AntixK/PyTorch-VAE#27]
Hi, I'm new to pytorch and VAEs in general. I attempted to run your VanillaVAE but I can't figure out how to reference the dataset inside the config file. Specifically, this is my folder structure:

![immagine](https://user-images.githubusercontent.com/17254471/112756724-ce38a180-8fe6-11eb-9d36-1e8c913a4083.png)

and my config looks like this:
```
exp_params:
  dataset: celeba
  data_path: "/content/drive/MyDrive/Colab/celeba"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
```

but still the error remains the same:
`RuntimeError: Dataset not found or corrupted. You can use download=True to download it`

Apart from the fact that using download=True doesn't work (looks like it attempts to download an invalid dataset), is there anything to take into account like unzipping the archive img_align_celeba.zip or stuff like that?
